# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# Execute workflow on push (develop/master) or pull request to any branch
on:
  issues:
    types: [opened]

jobs:
  fetch-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: echo ${{ toJson(github.event) }}