# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# Execute workflow on repository_dispatch event
on:
  repository_dispatch:
    types: start-swagger-workflow

jobs:
  fetch-source:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.repo_name }}