# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# Execute workflow on repository_dispatch event
on:
  repository_dispatch:
    types: start-swagger-workflow

jobs:
  job1:
    name: Get repository list
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repositories
        id: set-matrix
        run: |
          jsonContent=`cat repo.json`
          echo "::set-output name=matrix::$( echo $jsonContent )"

  fetch-source:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - name: Checkout ${{ matrix.repositories }}
        uses: actions/checkout@v2
        with:
          repository: vik-m/${{ matrix.repositories }}
          ref: master
          token: ${{ secrets.API_GITHUB_TOKEN }}
          
      - name: Change name
        run: mv input/test.json input/${{ matrix.repositories }}.json

      - name: Archive file
        uses: actions/upload-artifact@v2
        with:
          path: input/${{ matrix.repositories }}.json

  build:
    runs-on: ubuntu-latest
    needs: [fetch-source]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: output

      - name: Log
        run: ls -R
