# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# Execute workflow on push (develop/master) or pull request to any branch
on:
  create:
    branches:
      - vik-m/push-source

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: repo-sync/pull-request@v2
        with:
          pr_reviewer: vik-m
          github_token: ${{ secrets.API_GITHUB_TOKEN }}