# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# Execute workflow on repository_dispatch event
on:
  repository_dispatch:
    types: start-swagger-workflow

jobs:
  fetch-source:
    strategy:
      matrix:
        repo: [push-source, push-source2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v2
        with:
          repository: vik-m/${{ matrix.repo }}
          ref: master
          token: ${{ secrets.API_GITHUB_TOKEN }}
          
      - name: Change name
        run: mv input/test.json input/${{ matrix.repo }}.json

      - name: Archive file
        uses: actions/upload-artifact@v2
        with:
          path: input/${{ matrix.repo }}.json

  build:
    runs-on: ubuntu-latest
    needs: [fetch-source]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: output

      - name: Log
        run: ls -R
